server:
  servlet:
    context-path: /api

spring:
  application:
    name: spring-boot-web-mvc

  datasource:
    url: "jdbc:mysql://mysql-service:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true"
    username: "userapp"
    password: "user1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect




